remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: Modern Milkman Udder
description: Internal tools distribution repository
# Theme settings
show_downloads: false
google_analytics:
favicon: https://themodernmilkman.co.uk/favicon.ico

# Exclude APT repository files from Jekyll processing
exclude:
  - /apt
  - KEY.gpg

# Keep specific directories as-is (no Jekyll processing)
keep_files:
  - apt
  - KEY.gpg

# Configure GitHub Pages
github:
  is_project_page: true
  repository_url: https://github.com/modern-milkman/udder
